name: Deploy
on:
  push:
    tags:
      - release/[1-9]+.[0-9]+.[0-9]+
jobs:

  dockerSetup:
    name: Setup and build docker
    runs-on: ubuntu-latest

    env:
      OWNER: mrbelka12000

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo ${{ secrets.PASSWORD }} | docker login -u mrbelka12000  --password-stdin 

      - name: Docker build
        run: |
          docker build  -f build/Dockerfile -t mrbelka12000/mini_wiki:latest .

      - name: Docker push
        run: |
          docker push mrbelka12000/mini_wiki:latest

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: [dockerSetup]
    environment:
      name: production
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: copy builds to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_IP }} "docker service update --force --image mrbelka12000/mini_wiki:latest mini_wiki_service"
